services:

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=118
      - PGID=65534
      - TZ=****
      - UMASK_SET=022
      - WEBUI_PORT=8091
    volumes:
      - /srv/torrenting-stack/dockerdata/qbt/config:/config
      - /srv/dev-disk-by-uuid-******/mnt/ssd/Downloads:/downloads
      - /srv/dev-disk-by-uuid-******/mnt/ssd/Seeding:/seeding
    restart: unless-stopped
    ports:
      - 8091:8091
    networks:
      - default

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=118
      - PGID=65534
      - TZ=****
    volumes:
      - /srv/torrenting-stack/dockerdata/prowlarr:/config
    restart: unless-stopped
    ports:
      - 9696:9696
    networks:
      - default

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=118
      - PGID=65534
      - TZ=****
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/torrenting-stack/dockerdata/sonarr/config:/config
      - /srv/tvshows:/tvshows  
      - /srv/Qbittorrent/Downloads:/downloads
    restart: unless-stopped
    ports:
      - 8989:8989
    networks:
      - default

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=118
      - PGID=65534
      - TZ=**** 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/torrenting-stack/dockerdata/radarr/config:/config
      - /srv/Qbittorrent/FilmDownloads:/downloads
      - /srv/movies:/movies
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - default


