services:

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=118
      - PGID=65534
      - TZ=Asia/Kolkata  # Set timezone to India
      - UMASK_SET=022
      - WEBUI_PORT=8091
    volumes:
      - /srv/torrenting-stack/dockerdata/qbt/config:/config
      - /srv/dev-disk-by-uuid-9dbf2b75-e0d6-450b-95d2-99cd172c65ce/mnt/ssd/Downloads:/downloads
      - /srv/dev-disk-by-uuid-9dbf2b75-e0d6-450b-95d2-99cd172c65ce/mnt/ssd/Seeding:/seeding
    restart: unless-stopped
    ports:
      - 8091:8091
    networks:
      - default

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=118
      - PGID=65534
      - TZ=Asia/Kolkata  # Set timezone to India
    volumes:
      - /srv/torrenting-stack/dockerdata/prowlarr:/config
    restart: unless-stopped
    ports:
      - 9696:9696
    networks:
      - default

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=118
      - PGID=65534
      - TZ=Asia/Kolkata  # Set timezone to India
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/torrenting-stack/dockerdata/sonarr/config:/config
      - /srv/tvshows:/tvshows  # Assuming /srv/tvshows is the directory where your TV shows are stored
      - /srv/Qbittorrent/Downloads:/downloads  # Adjust to match the download directory used by qBittorrent
    restart: unless-stopped
    ports:
      - 8989:8989
    networks:
      - default

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=118
      - PGID=65534
      - TZ=Asia/Kolkata  # Set timezone to India
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/torrenting-stack/dockerdata/radarr/config:/config
      - /srv/Qbittorrent/FilmDownloads:/downloads  # Adjust to match the download directory used by qBittorrent
      - /srv/movies:/movies  # Assuming /srv/movies is the directory where your movies are stored
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - default


